### ISSUE TITLE
No output in Python 3.8.1 or 3.7.7

### ISSUE THREAD

**Issue by HWO365manager** [BennyCarbajal/PyTherm#3]
Running Python V3.8.1
All I get is:-
Hardware Monitor:
<function main at 0x05D7F2B8> although the 0x address changes.
Tested in V3.7.7 same result.
Running pythonnet 2.4.0

**Comment by xedret** [comment]
Currently PyTherm only works with python 2.7.15 and 2.7.17.

**Comment by HWO365manager** [comment]
Pity this information is not in the ReadMe!
It would have saved me hours of trying to work out why it was not working.

**Comment by xedret** [comment]
Literally the second line of the readme says Python 2

**Comment by HWO365manager** [comment]
So sorry. Need my eyes testing :-)
